// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_T7ChPp-hmxgFld1-MkNeleRjxi1jOP0',
    appId: '1:561599163621:web:1d1e7579513a8d9986780c',
    messagingSenderId: '561599163621',
    projectId: 'quizmaster-903a6',
    authDomain: 'quizmaster-903a6.firebaseapp.com',
    storageBucket: 'quizmaster-903a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_s1Nd9g_cFPbfV2l5EA1O7YhPFTjyMXg',
    appId: '1:561599163621:android:1b189147b487178086780c',
    messagingSenderId: '561599163621',
    projectId: 'quizmaster-903a6',
    storageBucket: 'quizmaster-903a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9DDZyawrSmGZ_ASz8GvtBE-04UUvHQA',
    appId: '1:561599163621:ios:cc75a863d5084e7b86780c',
    messagingSenderId: '561599163621',
    projectId: 'quizmaster-903a6',
    storageBucket: 'quizmaster-903a6.firebasestorage.app',
    iosClientId: '561599163621-4s4f69rkmhhil0bi0m4a9jpj6s7ma4m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq9DDZyawrSmGZ_ASz8GvtBE-04UUvHQA',
    appId: '1:561599163621:ios:cc75a863d5084e7b86780c',
    messagingSenderId: '561599163621',
    projectId: 'quizmaster-903a6',
    storageBucket: 'quizmaster-903a6.firebasestorage.app',
    iosClientId: '561599163621-4s4f69rkmhhil0bi0m4a9jpj6s7ma4m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_T7ChPp-hmxgFld1-MkNeleRjxi1jOP0',
    appId: '1:561599163621:web:b7588b992238db3986780c',
    messagingSenderId: '561599163621',
    projectId: 'quizmaster-903a6',
    authDomain: 'quizmaster-903a6.firebaseapp.com',
    storageBucket: 'quizmaster-903a6.firebasestorage.app',
  );
}
